apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: crudgolang
  name: crudgolang
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: crudgolang
    spec:
      containers:
      - env:
        - name: GET_HOST_FROM
          value: dns
        - name: POSTGRES_DB
          value: crud_name
        - name: POSTGRES_PASWORD
          value: crudpassword
        - name: POSTGRES_USER
          value: postgress-crud
        image: postgres
        name: cruddb
        ports:
        - containerPort: 5432
        resources: {}
      hostname: crudgolang
      restartPolicy: Always
status: {}
